3 your first ticket a fancy button peter and teddy
JumboCode/theatre-at-first pull request #10
Opened 2023-10-31 01:09 UTC by pmorganelli

finished button!!!!!

2023-10-31 15:47 UTC, liam-strand requested changes

2023-10-31 15:47 UTC, liam-strand commented on src/components/button5.tsx
> +                        <p className="text-center font-bold">Dream harder. We are in New England. {weather.probabilityOfPrecipitation.value}% chance of rain today.</p>
My system is getting angry at the `weather.probabilityOfPrecipitation.value` line, saying that `weather.probabilityOfPrecipitation` doesn't have a member `value`. It is declared as a `string[]` on line 10, after all. 

I also am not seeing any number on the button, just the percent sign.

Maybe worth taking another look? Make sure you are running this with our version of node? It is also possible there is an issue on my end

2023-10-31 15:47 UTC, liam-strand commented on src/components/button5.tsx
> +                        <p className="text-center font-bold">Your wish has been granted. {weather.probabilityOfPrecipitation.value}% chance of rain today.</p>
I love the snark :)

2023-10-31 15:49 UTC, liam-strand commented on src/components/button5.tsx
> +                        <p className="text-center font-bold">Dream harder. We are in New England. {weather.probabilityOfPrecipitation.value}% chance of rain today.</p>
Ah i looked a little closer, it looks like the `value` could be null, which needs to be handled specially.

2023-10-31 16:19 UTC, teddyh-io commented
How could the value even be null? Does that mean 0% chance of rain? 🤣

2023-10-31 17:31 UTC, pmorganelli commented
Yeah we were talking about this yesterday -- what should we do in this case?

On Tue, Oct 31, 2023 at 12:19 PM teddyh-io ***@***.***> wrote:

> How could the value even be null? Does that mean 0% chance of rain? 🤣
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JumboCode/theatre-at-first/pull/10#issuecomment-1787550326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BC7EJ5T4MIPIY7JRYIBLWQ3YCEQIRAVCNFSM6AAAAAA6W4R2VGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBXGU2TAMZSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-31 17:34 UTC, liam-strand commented
I'd take `null` as `0`. In the real world we'd look up what `null` means in the API, but here you can just do whatever you want.

2023-11-01 21:03 UTC, anott03 commented
#### In regards to the `null` issue:
To be thorough and make the typescript compiler happy, we need to check that every property on an object exists because we do not have a type for the `weather` object. So, for `weather.probabilityOfPrecipitation.value`, we need to know first that `weather` is not null. Then, once we know that, we need to ask "is `weather.probabilityOfPrecipitation`" null? And then the same thing for `weather.probabilityOfPrecipitation.value`.

The reason for this is that `weather` is type `any`, so typescript has no way of knowing what properties it should have and what the types of those properties should be. If this was going to be something we used in the long term, I would declare my own type along the lines of:

```typescript
type WeatherData {
    probabilityOfPrecipitation: {
        value: number
    }
}
```

2023-11-01 21:17 UTC, anott03 requested changes
Looks good! Just address the type issue and you should be all set. If you have questions about how you might go about doing that, I'm happy to provide some guidance.

2023-11-06 00:17 UTC, anott03 approved these changes
lovely

2023-11-06 00:18 UTC, merged