prettier
JumboCode/theatre-at-first pull request #84
Opened 2024-04-06 05:04 UTC by liam-strand

2024-04-09 16:07 UTC, liam-strand reviewed
Fantastic work Ben, thank you so much for your work on this.

2024-04-09 16:13 UTC, benborgers commented
I can delete the Worker code if that sounds good?

2024-04-09 16:14 UTC, liam-strand commented
Sounds good, it'll be in the git history if we need it later anyways.

2024-04-11 03:13 UTC, anott03 requested changes

2024-04-11 03:48 UTC, benborgers commented on src/components/image-capture-and-upload-component.tsx
> +        height: 1920,
I made it vertical because I was imagining this on a phone, but I'm not sure whether that's a reasonable assumption?

2024-04-16 18:21 UTC, anott03 commented on src/components/image-capture-and-upload-component.tsx
> +        height: 1920,
Oh that seems reasonable -- in which case it looks good!

2024-04-16 18:22 UTC, anott03 approved these changes

2024-04-16 18:23 UTC, merged